### ISSUE TITLE
[Error] torchaudio cannot load Path object when using sox backend

### ISSUE THREAD

**Issue by yoyololicon** [microsoft/fadtk#14]
As the title said, the following line can trigger an error when only `sox` is available as torchaudio backend.

https://github.com/microsoft/fadtk/blob/6d669c6cbf40187e288b03d15a25c79931239c6f/fadtk/model_loader.py#L141

This is because `sox` [does not support file-like objects](https://pytorch.org/audio/2.1.2/torchaudio.html#backend-and-dispatcher).
Passing `str(wav_file)` instead of `wav_file` could solve the issue.

**Comment by hykilpikonna** [comment]
Thanks for reporting the issue! It has been fixed!

**Comment by yoyololicon** [comment]
Hi @hykilpikonna,
I recently returned to this package and found that there are still a few places where this error could occur.
Any `torchaudio.load/save` should use a string filename.

There's one:
https://github.com/microsoft/fadtk/blob/39d620e91f7d8388b7f010921353304d108724f6/fadtk/fad.py#L146

There's another one:
https://github.com/microsoft/fadtk/blob/39d620e91f7d8388b7f010921353304d108724f6/fadtk/fad.py#L157

It would be great to have them resolved, as Sox backend is very common.
