### ISSUE TITLE
Problems with `python -m fadtk.test`

### ISSUE THREAD

**Issue by Fixei** [microsoft/fadtk#35]
Hey!
I'm on a 2,3 GHz 8-Core Intel Core i9 MacBook pro with macOS sonoma 14.7, using a zsh shell.

Setup steps were:
`pyenv local 3.11.0`
`python -m venv venv`
`source venv/bin/activate`
`pip install torch torchvision`
`pip install fadtk`

When running either of the following prompts, an error occurs:
`python -m fadtk.test` , `fadtk clap-laion-audio fma_pop /Users/stoeckl/Desktop/Fadtk/EvaluationSet --inf`, or `fadtk clap-laion-audio /Users/stoeckl/Desktop/Fadtk/Baseline /Users/stoeckl/Desktop/Fadtk/EvaluationSet --indiv`

![Image](https://github.com/user-attachments/assets/40aa1bb0-eaf2-4bef-bba7-d0cbcba82739)

![Image](https://github.com/user-attachments/assets/f4ab4c35-eec1-46d4-a819-facd5d6feb6e)

Any ideas how to solve this?

**Comment by hykilpikonna** [comment]
Should be fixed now. Please `pip install git+https://github.com/microsoft/fadtk` and try again
