### ISSUE TITLE
Question About Increasing FAD Scores in Individual Results

### ISSUE THREAD

**Issue by ndrw1221** [microsoft/fadtk#36]
Hi,

I encountered a potential issue while running the following command:

```
fadtk encodec-emb fma_pop /path/to/my/dataset/ --indiv
```

The results were saved in fad-individual-results.csv. Upon inspecting the file, I noticed that the FAD scores computed for each audio file seem to consistently increase. Below is a subset of the results:

```
/path/to/my/dataset/176321.wav,40.34934561349655
/path/to/my/dataset/132570.wav,49.611039323471005
/path/to/my/dataset/53296.wav,51.00401951301353
/path/to/my/dataset/325185.wav,53.68552529970327
/path/to/my/dataset/93636.wav,53.82833221221222
...
/path/to/my/dataset/160988.wav,306.8640716569905
/path/to/my/dataset/21144.wav,306.8897782043531
/path/to/my/dataset/34895.wav,307.00182878890996
/path/to/my/dataset/102470.wav,307.3313776150094
/path/to/my/dataset/220575.wav,307.38404974506875
```

This increasing trend in scores has raised some questions:
	1.	Is this behavior expected as part of the design of the tool?
	2.	Could there be an issue in the computation or configuration that led to this trend?

I would greatly appreciate any clarification or guidance on this. Let me know if additional details or the full dataset would help in diagnosing the issue.

Thanks in advance for your help!

**Comment by hykilpikonna** [comment]
> Is this behavior expected as part of the design of the tool?

Yes, if you look at the code, it's intentionally sorted by score.

**Comment by ndrw1221** [comment]
Understood. Thank you for the clarification!
